version: 2.1

references:
  workspace_root: &workspace_root
    /tmp/ni-workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: *workspace_root
      paths:
        - .

  ###################################
  # Install packages

  install_luarocks: &install_luarocks
    run:
      name: install luarocks
      command: |
        LUA_VERSION="5.3.5"
        LUAROCKS_VERSION="3.8.0"
        sudo apt-get update
        sudo apt-get install build-essential libreadline-dev unzip

        # install lua
        curl -R -O http://www.lua.org/ftp/lua-$LUA_VERSION.tar.gz
        tar -zxf lua-$LUA_VERSION.tar.gz
        cd lua-$LUA_VERSION
        make linux test
        sudo make install
        cd -

        # install luarocks
        wget https://luarocks.org/releases/luarocks-$LUAROCKS_VERSION.tar.gz
        tar zxpf luarocks-$LUAROCKS_VERSION.tar.gz
        cd luarocks-$LUAROCKS_VERSION
        ./configure --with-lua-include=/usr/local/include
        make
        sudo make install
        cd -

executors:
  default:
    docker:
      - image: cimg/base:stable
    working_directory: *workspace_root
    resource_class: small
  vm:
    machine:
      image: ubuntu-2204:2022.04.1
    working_directory: *workspace_root
    resource_class: medium

jobs:
  setup_workspace:
    executor: default
    steps:
      - checkout
      - {{ tmpl.Exec "step_ci_tools_checkout" | indent 8 | strings.TrimSpace }}
      - {{ include "step_ci_tools_config_check" | indent 8 | strings.TrimSpace }}
      - *persist_to_workspace

  test:
    executor: vm
    steps:
      - *attach_workspace
      - run:
          name: check that the version in rockspec file has been updated
          command: make check-release
      - run: make test

  build:
    executor: default
    steps:
      - *attach_workspace
      - *install_luarocks
      - run: make build
      - *persist_to_workspace

  release:
    executor: default
    steps:
      - *attach_workspace
      - {{ tmpl.Exec "step_install_jq" | indent 8 | strings.TrimSpace }}
      - {{ tmpl.Exec "step_install_github_cli" (dict "yq" false) | indent 8 | strings.TrimSpace }}
      - run: make release

workflows:
  version: 2
  main:
    jobs:
      - setup_workspace
      - test:
          requires:
            - setup_workspace
      - build:
          requires:
            - test
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
